### ISSUE TITLE
Doesnt seem to work at all

### ISSUE THREAD

**Issue by mastersuleman** [dekuScrub731/interactable#3]
Nothing happens at all when trying to use this?

**Comment by tcpowell** [comment]
Did you configure the Toggle Overlay? It isn't bound to a key on initial install:
![image](https://user-images.githubusercontent.com/123216941/215005254-773613e5-46a7-4cec-80f7-4fa69ffca89e.png)

**Comment by mastersuleman** [comment]
Right, so it turns out that I'm an idiot. Thank you very much for this plugin btw. I was looking for something that would highlight npc's that you cannot attack but you can interact with and have their name above their head. I couldnt find anything like that except NPC indicators but then i'd have to manually untag everything else or manually tag everything.

This is good enough to highlight interactable npcs. So thank you very much
